complexity:
  LongParameterList:
    active: true
    functionThreshold: 5
    constructorThreshold: 7
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotated: [ 'Composable', 'Test' ]
  ComplexCondition:
    active: true
    ignoreAnnotated: [ 'Composable', 'Test' ]
  CyclomaticComplexMethod:
    active: true
    ignoreAnnotated: [ 'Composable', 'Test' ]
  LongMethod:
    active: true
    threshold: 40
    ignoreAnnotated: [ 'Composable', 'Test' ]
  NestedBlockDepth:
    active: true
    threshold: 4
    ignoreAnnotated: [ 'Composable', 'Test' ]
  TooManyFunctions:
    active: true
    thresholdInFiles: 30
    thresholdInClasses: 20
    thresholdInInterfaces: 10
    thresholdInObjects: 20
    thresholdInEnums: 5
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: false
    ignoreAnnotated: [ 'Composable', 'Test' ]
  LargeClass:
    active: true
    threshold: 500

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'preview' ]

naming:
  active: true
  BooleanPropertyNaming:
    active: true
    ignoreAnnotated: [ 'IgnoreDetektNaming' ]
  NonBooleanPropertyPrefixedWithIs:
    active: true
    ignoreAnnotated: [ 'IgnoreDetektNaming' ]
  NoNameShadowing:
    active: true
    ignoreAnnotated: [ 'IgnoreDetektNaming' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
    ignoreAnnotated: [ 'IgnoreDetektNaming' ]
  FunctionNaming:
    ignoreAnnotated: [ 'Composable', 'Test', 'IgnoreDetektNaming' ]
  MatchingDeclarationName:
    active: false


output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'

potential-bugs:
  active: true
  HasPlatformType:
    active: true

performance:
  active: true
  SpreadOperator:
    active: false